version: '3.1'
services:
  mongo:
    image: mongo
    container_name: from-you-mongo
    env_file:
      - .env
    ports:
      - 27017:27017
  neo4j:
    image: neo4j
    container_name: from-you-neo4j
    ports:
      - 7474:7474
      - 7687:7687
